lsi: false
safe: false
url: "https://play.onions.life"
source: .
title: Onion's Life
tagline: An EPIC game for web where you impersonate an Onion and go on adventures through mazes and labyrinths.
google_site_verification: -GirfHk5Bkl4sgo0-T48i6fwng9-0ccDyy3xK-Irm7E
logo: /assets/sprites/onion.png
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
