lsi: false
safe: false
url: "https://play.onions.life"
source: .
title: Onion's Life
tagline: An EPIC game for web where you impersonate an Onion and go on adventures through mazes and labyrinths.
description: In this video game, go on the journey of an Onion, as you venture through a world of spikes, ghosts, coins, and keys. Surprises and mysteries abound in this game, never knowing what could lie on the other side of the portal.
google_site_verification: -GirfHk5Bkl4sgo0-T48i6fwng9-0ccDyy3xK-Irm7E
logo: /assets/sprites/onion.png
incremental: false
highlighter: rouge
author: Onion's Life
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
